ted_iso2tag = {
    'arb': 'ar',
    'azj': 'az', #aze
    'aze': 'az', #aze
    'bel': 'be',
    'bul': 'bg',
    'ben': 'bn',
    'bos': 'bs',
    'ces': 'cs',
    'dan': 'da',
    'deu': 'de',
    'ell': 'el',
    'epo': 'eo',
    'spa': 'es',
    'est': 'et',
    'eus': 'eu',
    'pes': 'fa', #fas
    'fin': 'fi',
    'fra': 'fr',
    'glg': 'gl',
    'heb': 'he',
    'hin': 'hi',
    'hrv': 'hr',
    'hun': 'hu',
    'hye': 'hy',
    'ind': 'id',
    'ita': 'it',
    'jpn': 'ja',
    'kat': 'ka',
    'kaz': 'kk',
    'kor': 'ko',
    'kur': 'ku',
    'lit': 'lt',
    'mkd': 'mk',
    'khk': 'mn', #mon
    'mon': 'mn', #mon
    'mar': 'mr',
    'zlm': 'ms',
    'mya': 'my',
    'nob': 'nb',
    'nld': 'nl',
    'pol': 'pl',
    'por': 'pt',
    'ron': 'ro',
    'rus': 'ru',
    'slk': 'sk',
    'slv': 'sl',
    'alb': 'sq', #sqi
    'sqi': 'sq', #sqi
    'srp': 'sr',
    'swe': 'sv',
    'tam': 'ta',
    'tha': 'th',
    'tur': 'tr',
    'ukr': 'uk',
    'urd': 'ur',
    'vie': 'vi',
    'cmn': 'zh'
}

ted_tag2iso = {
    'ar': 'arb',
    'az': 'azj', #aze
    'be': 'bel',
    'bg': 'bul',
    'bn': 'ben',
    'bs': 'bos',
    'cs': 'ces',
    'da': 'dan',
    'de': 'deu',
    'el': 'ell',
    #'eo': 'epo',
    'es': 'spa',
    'et': 'est',
    'eu': 'eus',
    'fa': 'pes', #fas
    'fi': 'fin',
    'fr': 'fra',
    'gl': 'glg',
    'he': 'heb',
    'hi': 'hin',
    'hr': 'hrv',
    'hu': 'hun',
    'hy': 'hye',
    'id': 'ind',
    'it': 'ita',
    'ja': 'jpn',
    'ka': 'kat',
    'kk': 'kaz',
    'ko': 'kor',
    'ku': 'kur',
    'lt': 'lit',
    'mk': 'mkd',
    'mn': 'mon',
    'mr': 'mar',
    'ms': 'zlm',
    'my': 'mya',
    'nb': 'nob',
    'nl': 'nld',
    'pl': 'pol',
    'pt': 'por',
    'ro': 'ron',
    'ru': 'rus',
    'sk': 'slk',
    'sl': 'slv',
    'sq': 'alb', #sqi
    'sr': 'srp',
    'sv': 'swe',
    'ta': 'tam',
    'th': 'tha',
    'tr': 'tur',
    'uk': 'ukr',
    'ur': 'urd',
    'vi': 'vie',
    'zh': 'cmn'
}

ted_iso2name = {
    'arb': 'Arabic',
    
    'aze': 'Azerbaijani',
    'azj': 'NorthAzerbaijani',
    
    'bel': 'Belarusian',
    'bul': 'Bulgarian',
    'ben': 'Bengali',
    'bos': 'Bosnian',
    'ces': 'Czech',
    'dan': 'Danish',
    'deu': 'German',
    'ell': 'Greek',
    #'epo': 'Esperanto',
    'spa': 'Spanish',
    'est': 'Estonian',
    'eus': 'Basque',
    #'fas': 'Persian',
    'pes': 'Persian',
    'fin': 'Finnish',
    'fra': 'French',
    'glg': 'Galician',
    'heb': 'Hebrew',
    'hin': 'Hindi',
    'hrv': 'Croatian',
    'hun': 'Hungarian',
    'hye': 'Armenian',
    'ind': 'Indonesian',
    'ita': 'Italian',
    'jpn': 'Japanese',
    'kat': 'Georgian',
    'kaz': 'Kazakh',
    'kor': 'Korean',
    'kur': 'Kurdish',
    'lit': 'Lithuanian',
    'mkd': 'Macedonian',
    
    'mon': 'Mongolian',
    'khk': 'HalhMongolian',
    
    'mar': 'Marathi',
    'zlm': 'Malay',
    'mya': 'Burmese',
    'nob': 'Nor. Bokmål', # 'NorwegianBokmål',
    'nld': 'Dutch',
    'pol': 'Polish',
    'por': 'Portuguese',
    'ron': 'Romanian',
    'rus': 'Russian',
    'slk': 'Slovak',
    'slv': 'Slovenian',

    'alb': 'Albanian', #sqi
    'sqi': 'Albanian', 
    
    'srp': 'Serbian',
    'swe': 'Swedish',
    'tam': 'Tamil',
    'tha': 'Thai',
    'tur': 'Turkish',
    'ukr': 'Ukrainian',
    'urd': 'Urdu',
    'vie': 'Vietnamese',
    'cmn': 'Chinese'
}

#print(", ".join("\"%s\""%l for l in ted_iso2tag.keys()))

# No Esperando! "epo"
#ted_iso_langs = ["arb", "azj", "bel", "bul", "ben", "bos", "ces", "dan", "deu", "ell", "spa", "est", "eus", 
#                 "pes", "fin", "fra", "glg", "heb", "hin", "hrv", "hun", "hye", "ind", "ita", "jpn", "kat", "kaz", 
#                 "kor", "kur", "lit", "mkd", "khk", "mar", "zlm", "mya", "nob", "nld", "pol", "por", "ron", "rus", 
#                 "slk", "slv", "alb", "srp", "swe", "tam", "tha", "tur", "ukr", "urd", "vie", "cmn"]
ted_iso_langs = ["arb", "aze", "bel", "bul", "ben", "bos", "ces", "dan", "deu", "ell", "spa", "est", "eus", 
                 "pes", "fin", "fra", "glg", "heb", "hin", "hrv", "hun", "hye", "ind", "ita", "jpn", "kat", "kaz", 
                 "kor", "kur", "lit", "mkd", "mon", "mar", "zlm", "mya", "nob", "nld", "pol", "por", "ron", "rus", 
                 "slk", "slv", "sqi", "srp", "swe", "tam", "tha", "tur", "ukr", "urd", "vie", "cmn"]

'''
ara -> arb (Standard Arabic)
zho -> cmn
epo -> NO!!! (Esperanto)
fas -> pes
mon -> Mongolian is a macrolanguage, then... HalhMongolian (khk) or PeripheralMongolian	(mvf)?

aze -> azj or azb ? 
https://en.wikipedia.org/wiki/Azerbaijani_language#North_vs._South_Azerbaijani
NorthAzerbaijani (azj) is spoken in Azerbajan... so?
'''

ted_tag2family = {
    'ar': 'Afroasiatic',
    'az': 'Turkic',
    'be': 'Indo-European/Balto-Slavic',
    'bg': 'Indo-European/Balto-Slavic',
    'bn': 'Indo-European/Indo-Iranian',
    'bs': 'Indo-European/Balto-Slavic',
    'cs': 'Indo-European/Balto-Slavic',
    'da': 'Indo-European/Germanic',
    'de': 'Indo-European/Germanic',
    'el': 'Indo-European/Hellenic',
    'eo': 'N.A.',
    'es': 'Indo-European/Italic/Romance',
    'et': 'Uralic',
    'eu': 'Vasconic?',
    'fa': 'Indo-European/Indo-Iranian',
    'fi': 'Uralic',
    'fr': 'Indo-European/Italic/Romance',
    'gl': 'Indo-European/Italic/Romance',
    'he': 'Afroasiatic',
    'hi': 'Indo-European/Indo-Iranian',
    'hr': 'Indo-European/Balto-Slavic',
    'hu': 'Uralic',
    'hy': 'Indo-European/Armenian',
    'id': 'Austronesian',
    'it': 'Indo-European/Italic/Romance',
    'ja': 'Japonic',
    'ka': 'Kartvelian',
    'kk': 'Turkic',
    'ko': 'Koreanic',
    'ku': 'Indo-European/Indo-Iranian',
    'lt': 'Indo-European/Balto-Slavic',
    'mk': 'Indo-European/Balto-Slavic',
    'mn': 'Mongolic',
    'mr': 'Indo-European/Indo-Iranian',
    'ms': 'Austronesian',
    'my': 'Sino-Tibetan',
    'nb': 'Indo-European/Germanic',
    'nl': 'Indo-European/Germanic',
    'pl': 'Indo-European/Balto-Slavic',
    'pt': 'Indo-European/Italic/Romance',
    'ro': 'Indo-European/Italic/Romance',
    'ru': 'Indo-European/Balto-Slavic',
    'sk': 'Indo-European/Balto-Slavic',
    'sl': 'Indo-European/Balto-Slavic',
    'sq': 'Indo-European/Albanian',
    'sr': 'Indo-European/Balto-Slavic',
    'sv': 'Indo-European/Germanic',
    'ta': 'Dravidian',
    'th': 'Kra-Dai',
    'tr': 'Turkic',
    'uk': 'Indo-European/Balto-Slavic',
    'ur': 'Indo-European/Indo-Iranian',
    'vi': 'Austroasiatic',
    'zh': 'Sino-Tibetan'
}

ted_family2tag = {
    'Afroasiatic': ['ar', 'he'],
    'Austroasiatic': ['vi'],
    'Austronesian': ['id', 'ms'],
    'Dravidian': ['ta'],
    'Indo-European/Albanian': ['sq'],
    'Indo-European/Armenian': ['hy'],
    'Indo-European/Balto-Slavic': ['be', 'bg', 'bs', 'cs', 'hr', 'lt', 'mk', 'pl', 'ru', 'sk', 'sl', 'sr', 'uk'],
    'Indo-European/Germanic': ['da', 'de', 'nb', 'nl', 'sv'],
    'Indo-European/Hellenic': ['el'],
    'Indo-European/Indo-Iranian': ['bn', 'fa', 'hi', 'ku', 'mr', 'ur'],
    'Indo-European/Italic/Romance': ['es', 'fr', 'gl', 'it', 'pt', 'ro'],
    'Japonic': ['ja'],
    'Kartvelian': ['ka'],
    'Koreanic': ['ko'],
    'Kra-Dai': ['th'],
    'Mongolic': ['mn'],
    #'N.A.': ['eo'],
    'Sino-Tibetan': ['my', 'zh'],
    'Turkic': ['az', 'kk', 'tr'],
    'Uralic': ['et', 'fi', 'hu'],
    'Vasconic?': ['eu']
}

'''
families = sorted(list(set(ted_tag2family.values())))
ted_family2tag = {}
for fam in families:
    ted_family2tag[fam] = []
for k,v in ted_tag2family.items():
    ted_family2tag[v].append(k)
for fam in families:
    print("'%s': [%s]," % (fam, ", ".join(sorted(["'%s'"%l for l in ted_family2tag[fam]]))))
'''

Baseline_Langs = {
    # Germanic
    'eng': 'English',
    'swe': 'Swedish', #no WIT
    'dan': 'Danish',  #no WIT
    'deu': 'German',
    'nld': 'Dutch',
    # Romanic
    'ron': 'Romanian',
    'fra': 'French',
    'ita': 'Italian',
    'spa': 'Spanish',
    'por': 'Portuguese',
    # Balco-Slavic
    'lav': 'Latvian',   #no WIT
    'lit': 'Lithuanian',#no WIT
    'pol': 'Polish',
    'slk': 'Slovak',
    'ces': 'Czech',
    'slv': 'Slovenian',
    'bul': 'Bulgarian'
}

all_iso2name = {
'arb': 'Arabic',
'heb': 'Hebrew',
'kab': 'Kabyle',
'vie': 'Vietnamese',
'ind': 'Indonesian',
'zlm': 'Malay',
'tgl': 'Tagalog',
'kan': 'Kannada',
'mal': 'Malay',
'tam': 'Tamil',
'tel': 'Telugu',
'sqi': 'Albanian',
'hye': 'Armenian',
'bel': 'Belarusian',
'bos': 'Bosnian',
'bul': 'Bulgarian',
'hrv': 'Croatian',
'ces': 'Czech',
'lit': 'Lithuanian',
'mkd': 'Macedonian',
'pol': 'Polish',
'rus': 'Russian',
'srp': 'Serbian',
'slk': 'Slovak',
'slv': 'Slovenian',
'ukr': 'Ukrainian',
'dan': 'Danish',
'nld': 'Dutch',
'eng': 'English',
'deu': 'German',
'isl': 'Icelandic',
'nds': 'Low Saxon',
'nob': 'Norwegian Bokmål',
'swe': 'Swedish',
'ell': 'Greek',
'asm': 'Assamese',
'ben': 'Bengali',
'guj': 'Gujarati',
'hin': 'Hindi',
'kur': 'Kurdish',
'mar': 'Marathi',
'ori': 'Odia',
'pes': 'Persian',
'pan': 'Punjabi',
'urd': 'Urdu',
'fra': 'French',
'glg': 'Galician',
'ita': 'Italian',
'por': 'Portuguese',
'ron': 'Romanian',
'spa': 'Spanish',
'jpn': 'Japanese',
'kat': 'Georgian',
'kor': 'Korean',
'tha': 'Thai',
'mon': 'Mongolian',
'shp': 'Shipibo-Konibo',
'mya': 'Burmese',
'cmn': 'Mandarin Chinese',
'mni': 'Manipuri',
'yue': 'Yue Chinese',
'aze': 'Azerbaijani',
'kaz': 'Kazakh',
'tur': 'Turkish',
'tuk': 'Turkmen',
'est': 'Estonian',
'fin': 'Finnish',
'hun': 'Hungarian',
'eus': 'Basque'
}

ted_tag2size = { 'kk': 3259, 
    'be': 4410, 
    'bn': 4552, 
    'eu': 5107, 
    'ms': 5120, 
    'bs': 5586, 
    'ur': 5858, 
    'az': 5863, 
    'ta': 6135, 
    'mn': 7461, 
    'mr': 9706, 
    'gl': 9870, 
    'ku': 10294, 
    'et': 10587, 
    'ka': 13010, 
    'nb': 15591, 
    'hi': 18517, 
    'sl': 19481, 
    'my': 20998, 
    'hy': 21060, 
    'fi': 23897, 
    'mk': 24993, 
    'lt': 41209, 
    'sq': 43823, 
    'da': 44269, 
    'pt': 50834, 
    'sv': 55696, 
    'sk': 60528, 
    'id': 85985, 
    'th': 96578, 
    'cs': 101614, 
    'uk': 106780, 
    'hr': 120148, 
    'el': 132254, 
    'sr': 134631, 
    'hu': 145039, 
    'fa': 148885, 
    'de': 165531, 
    'vi': 169731, 
    'bg': 172093, 
    'pl': 173813, 
    'ro': 178059, 
    'tr': 179930, 
    'nl': 181100, 
    'fr': 189444, 
    'es': 193075, 
    'zh': 197389, 
    'ja': 201421, 
    'it': 201575, 
    'ko': 202897, 
    'ru': 205458, 
    'he': 208693, 
    'ar': 211363 
}

all_iso_langs = list(all_iso2name.keys())

#print(" ".join(["<%s>|<%s>" % (ted_iso2tag[l], ted_iso2tag[l]) for l in ted_iso_langs]))